//! Golden byte-equality tests for the relocated "file" layer.
//!
//! These lock the **byte-equal contract** that crossplane-forge (and thus
//! a downstream vendor provider) depends on: the relocated `iac_forge::goast` printer
//! must produce output identical to the byte. Each test asserts on a full
//! literal string — not on substring presence — so any drift in the printer
//! is caught immediately.

use go_synthesizer::{
    GoBlock, GoDecl, GoExpr, GoField, GoFile, GoFuncDecl, GoImport, GoParam, GoRecv, GoStmt,
    GoStructTag, GoType, GoTypeBody, GoTypeDecl, GoVarDecl, JsonTag, KubeMarker, ResourceScope,
    YamlTag, print_file,
};

const HEADER: &str = "// Code generated by iac-forge. DO NOT EDIT.\n";

/// (a) A struct with a kubebuilder marker + json+yaml typed tags + an
/// embedded `Option` field (pointer type, the typical optional shape).
#[test]
fn golden_struct_with_markers_typed_tags_and_optional_field() {
    let mut f = GoFile::new("v1alpha1");
    f.decls.push(GoDecl::Type(GoTypeDecl {
        name: "FooParameters".to_string(),
        doc: Some("FooParameters define the desired state.".to_string()),
        markers: vec![KubeMarker::Resource {
            scope: ResourceScope::Cluster,
            categories: vec!["crossplane".to_string(), "managed".to_string()],
        }],
        body: GoTypeBody::Struct(vec![
            GoField {
                name: Some("Name".to_string()),
                ty: GoType::named("string"),
                doc: Some("Name is required.".to_string()),
                markers: vec![KubeMarker::Required],
                tags: vec![
                    GoStructTag::Json(JsonTag { name: "name".to_string(), ..Default::default() }),
                    GoStructTag::Yaml(YamlTag { name: "name".to_string(), ..Default::default() }),
                ],
            },
            GoField {
                name: Some("Description".to_string()),
                // *string — the canonical Go "Option" shape.
                ty: GoType::pointer(GoType::named("string")),
                doc: None,
                markers: vec![KubeMarker::Optional],
                tags: vec![GoStructTag::Json(JsonTag {
                    name: "description".to_string(),
                    omitempty: true,
                    inline: false,
                })],
            },
        ]),
    }));

    let expected = format!(
        "{HEADER}\n\
         package v1alpha1\n\
         \n\
         // FooParameters define the desired state.\n\
         // +kubebuilder:resource:scope=Cluster,categories={{crossplane,managed}}\n\
         type FooParameters struct {{\n\
         \t// Name is required.\n\
         \t// +kubebuilder:validation:Required\n\
         \tName string `json:\"name\" yaml:\"name\"`\n\
         \t// +optional\n\
         \tDescription *string `json:\"description,omitempty\"`\n\
         }}\n"
    );
    assert_eq!(print_file(&f), expected);
}

/// (b) A func with a receiver (`GoRecv`) and params.
#[test]
fn golden_func_with_receiver_and_params() {
    let mut body = GoBlock::new();
    body.push(GoStmt::Return(vec![GoExpr::nil()]));
    let f_decl = GoFuncDecl {
        name: "Observe".to_string(),
        doc: Some("Observe checks external state.".to_string()),
        recv: Some(GoRecv {
            name: "e".to_string(),
            ty: GoType::pointer(GoType::named("external")),
        }),
        params: vec![
            GoParam { name: "ctx".to_string(), ty: GoType::qualified("context", "Context") },
            GoParam { name: "mg".to_string(), ty: GoType::qualified("resource", "Managed") },
        ],
        returns: vec![GoType::named("error")],
        body,
    };
    let mut file = GoFile::new("controller");
    file.decls.push(GoDecl::Func(f_decl));

    let expected = format!(
        "{HEADER}\n\
         package controller\n\
         \n\
         // Observe checks external state.\n\
         func (e *external) Observe(ctx context.Context, mg resource.Managed) error {{\n\
         \treturn nil\n\
         }}\n"
    );
    assert_eq!(print_file(&file), expected);
}

/// (c) A `GoVarDecl` var declaration.
#[test]
fn golden_var_decl() {
    let mut file = GoFile::new("apis");
    file.decls.push(GoDecl::Var(GoVarDecl {
        name: "SchemeBuilder".to_string(),
        ty: None,
        value: Some(GoExpr::call(
            GoExpr::path(&["scheme", "Builder"]),
            vec![],
        )),
        doc: Some("SchemeBuilder registers types.".to_string()),
        block_id: None,
    }));
    file.decls.push(GoDecl::Var(GoVarDecl {
        name: "GroupVersion".to_string(),
        ty: Some(GoType::qualified("schema", "GroupVersion")),
        value: None,
        doc: None,
        block_id: None,
    }));

    let expected = format!(
        "{HEADER}\n\
         package apis\n\
         \n\
         // SchemeBuilder registers types.\n\
         var SchemeBuilder = scheme.Builder()\n\
         \n\
         var GroupVersion schema.GroupVersion\n"
    );
    assert_eq!(print_file(&file), expected);
}

/// (d) A whole `GoFile` with grouped + sorted stdlib vs third-party imports
/// and the DO-NOT-EDIT header.
#[test]
fn golden_whole_file_grouped_sorted_imports() {
    let mut f = GoFile::new("main");
    // Deliberately out of order to prove the printer sorts + groups.
    f.imports.push(GoImport::plain("github.com/example/zeta"));
    f.imports.push(GoImport::plain("fmt"));
    f.imports.push(GoImport::aliased("xpv1", "github.com/crossplane/crossplane-runtime/apis/common/v1"));
    f.imports.push(GoImport::plain("context"));

    let expected = format!(
        "{HEADER}\n\
         package main\n\
         \n\
         import (\n\
         \t\"context\"\n\
         \t\"fmt\"\n\
         \n\
         \txpv1 \"github.com/crossplane/crossplane-runtime/apis/common/v1\"\n\
         \t\"github.com/example/zeta\"\n\
         )\n"
    );
    assert_eq!(print_file(&f), expected);
}
